### ISSUE TITLE
Why won't this work?

### ISSUE THREAD

**Issue by mikestratton** [rally25rs/RockPaperBoom#4]
{
  start: function () {
      this.opponentPlayed = 0;
      var roc = 0;
      var pap = 0;
      var sis = 0;
      var wat = 0;
      var dyn = 0;
      
  },
 
  end: function () {
  },
 
  play: function () {
    

   if(sis >= 5)
    {
        return "R";
    }
	
	else if(roc >= 5)
    {
        return "P";
    }

    else if(pap >= 5)
    {
        return "S";
    }

    else if(wat >= 5)
    {
        return "R";
    }

    else if(dyn >= 5)
    {
        return "W";
    }

    else{
      return "R"; // R,P,S,D,W
	}
  
  },
 
  result: function (opponentPlayed, result) {

    this.opponentPlayed;

    if (opponentPlayed == "R") 
    {
        roc++;
    }
    else {roc = 0;}

    if (opponentPlayed == "P") 
    {
        pap++;
    }
    else {pap = 0;}

    if (opponentPlayed == "S") 
    {
        sis++;
    }
    else {sis = 0;}

    if (opponentPlayed == "D") 
    {
        dyn++;
    }
    else {dyn = 0;}

    if (opponentPlayed == "W") 
    {
        wat++;
    }
    else {wat = 0;} 

  }
}

**Comment by gvoudzon** [comment]
All the vars need to be changed to this.whatevers.   The bot = eval(code) will tease us into thinking that vars work by accepting one var,  but then when multiple vars are declared,  it fails then.   I tried it just now with all of the vars changed to this.whatevers and it works.
